const codes = [
    { code: "ADMIN_STRENGTH", reward: "20 minutos de 2x XP", expiry: "Sem expiração" },
    { code: "SUB2GAMERROBOT_RESET1", reward: "Reset de Estatísticas", expiry: "Sem expiração" },
    { code: "SUB2GAMERROBOT_EXP1", reward: "30 minutos de 2x XP", expiry: "Sem expiração" },
    { code: "SUB2NOOBMASTER123", reward: "15 minutos de 2x XP", expiry: "Sem expiração" },
    { code: "SUB2UNCLEKIZARU", reward: "Reset de Estatísticas", expiry: "Sem expiração" },
    { code: "SUB2DAIGROCK", reward: "15 minutos de 2x XP", expiry: "Sem expiração" },
    { code: "AXIORE", reward: "20 minutos de 2x XP", expiry: "Sem expiração" },
    { code: "TANTAI_GAMING", reward: "15 minutos de 2x XP", expiry: "Sem expiração" },
    { code: "STRAWHATMAINE", reward: "15 minutos de 2x XP", expiry: "Sem expiração" },
    { code: "UPD16", reward: "20 minutos de 2x XP", expiry: "Sem expiração" },
    { code: "FUDD10", reward: "$1", expiry: "Sem expiração" },
    { code: "BIGNEWS", reward: "Título no jogo", expiry: "Sem expiração" },
    { code: "THEGREATACE", reward: "20 minutos de 2x XP", expiry: "Sem expiração" },
    { code: "SUB2CAPTAINMAUI", reward: "20 minutos de 2x XP", expiry: "Sem expiração" },
    { code: "KITT_RESET", reward: "Reset de Estatísticas", expiry: "Sem expiração" },
    { code: "SUB2GAMERROBOT_RESET2", reward: "Reset de Estatísticas", expiry: "Sem expiração" },
    { code: "CHANDLER", reward: "Título no jogo", expiry: "Sem expiração" },
    { code: "DEVSCOOKING", reward: "Título no jogo", expiry: "Sem expiração" },
    { code: "STAFFBATTLE", reward: "Título no jogo", expiry: "Sem expiração" },
    { code: "DEVSCOOKING2", reward: "Título no jogo", expiry: "Sem expiração" },
    { code: "JULYUPDATE", reward: "20 minutos de 2x XP", expiry: "Expirado" },
    { code: "BLUXXY", reward: "Título no jogo", expiry: "Expirado" },
    { code: "KITTGAMING", reward: "20 minutos de 2x XP", expiry: "Expirado" },
    { code: "ENYU_IS_PRO", reward: "20 minutos de 2x XP", expiry: "Expirado" },
    { code: "MAGICBUS", reward: "20 minutos de 2x XP", expiry: "Expirado" },
    { code: "JCWK", reward: "20 minutos de 2x XP", expiry: "Expirado" },
    { code: "STARCODEHEO", reward: "20 minutos de 2x XP", expiry: "Expirado" },
    { code: "SUBGAMERROBOT_RESET", reward: "Reset de Estatísticas", expiry: "Expirado" }
];
